### ISSUE TITLE
ruby-hmac not working...

### ISSUE THREAD

**Issue by ehoch** [seomoz/linkscape-gem#4]
https://github.com/topfunky/ruby-hmac

ruby-hmac looks to be no longer maintained and I'm getting an error on OS X Mountain Lion:

```
RuntimeError: The underlying hash algorithm has not yet been initialized.
    from /Users/ehochber/.rvm/gems/ruby-1.9.3-p286@xenuranker/gems/ruby-hmac-0.4.0/lib/hmac.rb:29:in `check_status'
    from /Users/ehochber/.rvm/gems/ruby-1.9.3-p286@xenuranker/gems/ruby-hmac-0.4.0/lib/hmac.rb:60:in `update'
    from /Users/ehochber/.rvm/gems/ruby-1.9.3-p286@xenuranker/gems/ruby-hmac-0.4.0/lib/hmac.rb:91:in `digest'
    from /Users/ehochber/.rvm/gems/ruby-1.9.3-p286@xenuranker/gems/linkscape-0.3.2/lib/linkscape/signer.rb:8:in `signParams'
    from /Users/ehochber/.rvm/gems/ruby-1.9.3-p286@xenuranker/gems/linkscape-0.3.2/lib/linkscape/request.rb:61:in `signRequest'
    from /Users/ehochber/.rvm/gems/ruby-1.9.3-p286@xenuranker/gems/linkscape-0.3.2/lib/linkscape/request.rb:37:in `initialize'
```

**Comment by ehoch** [comment]
Hmm, user error.  Bad key.
